name: check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup latest deno version
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

# Disabled because it attempts to check result json files which will not work!
#      - name: Run deno fmt
#        run: deno fmt --check

#       - name: Run deno lint
#         run: deno lint --unstable
